persisten_storage_change
axetrading/terraform-helm-aws-deployment pull request #8
Opened 2023-10-13 13:48 UTC by viveksinghtt

@ursuciprian @tomyan

2023-10-17 05:30 UTC, ursuciprian requested changes

2023-10-17 05:30 UTC, ursuciprian commented on helm/axetrading-api/templates/deployment.yaml
> +volumeClaimTemplates:
Deployments don't have a volumeClaimTemplates field because they create replicas (pods) that are not intended to have unique identities or unique persistent storage. If you need a PVC for your Deployment, you typically define it separately and refer to it in your pod template's volumes section, but it won't be unique to each pod; each replica would end up using the same PVC, which could result in conflicts depending on the nature of the application and the storage system.

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

2023-10-17 09:18 UTC, viveksinghtt commented on helm/axetrading-api/templates/deployment.yaml
> +volumeClaimTemplates:
@ursuciprian @tomyan made the relevant changes.

2023-10-18 07:50 UTC, ursuciprian commented on variables.tf
>  variable "efs_role" {
what's the purpose of this variable?

2023-10-18 07:50 UTC, ursuciprian commented on variables.tf
>  variable "aws_region" {
the region will be dictated by the AWS Provider, not a variable. 
We are not doing cross-account / cross region references. Yet.

2023-10-18 07:50 UTC, ursuciprian commented on helm/axetrading-api/templates/persistent_volume_claim.yaml
this will generate a conflict. if persistance is enabled,  helm will try to create the claim based on this manifest. The same PVC will also be created by the statefulset spec : pvc template.

2023-10-18 07:50 UTC, ursuciprian commented on helm/axetrading-api/values.yaml.tpl
podAnnotationsstatefulset.iam.amazonaws.com/role: $efs_role. 
The role arn must be in SA annotations, not in PodAnnotations. If the purpose of this is pure cosmetic, please remove it. 
For RBAC in AWS EKS please refer to https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

2023-10-18 07:50 UTC, ursuciprian commented on helm/axetrading-api/templates/persistent_volume.yaml
https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/

2023-10-23 06:17 UTC, ursuciprian approved these changes

2023-10-23 06:17 UTC, merged